AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3

Resources:
  DemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: demo/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        Demo:
          Type: Api
          Properties:
            Path: /
            Method: get

Outputs:
  DemoApi:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  DemoFunction:
    Description: "SAM example"
    Value: !GetAtt DemoFunction.Arn
  DemoFunctionIamRole:
    Description: "Implicit IAM Role created for Demo function"
    Value: !GetAtt DemoFunctionRole.Arn
